#ifndef __ONLINE_GAME_GS_COOLDOWN_CONFIG_H__
#define __ONLINE_GAME_GS_COOLDOWN_CONFIG_H__

//单位为毫秒
#define EMOTE_COOLDOWN_TIME		1500
#define FASHION_COOLDOWN_TIME		4000
#define DROPMONEY_COOLDOWN_TIME		1671
#define DROPITEM_COOLDOWN_TIME  	321	
#define QUERY_OTHER_EQUIP_COOLDOWN_TIME	20000			//察看别人装备的冷却时间
#define FIREWORKS_COOLDOWN_TIME		800			//使用标准烟花的时间
#define SKILLTRIGGER_COOLDOWN_TIME	120000			//使用技能物品的冷却时间
#define COUPLE_JUMP_COOLDOWN_TIME	5000			//夫妻使用物品的冷却时间
#define LOTTERY_COOLDOWN_TIME		100			//彩票的冷却时间
#define RECORDER_COOLDOWN_TIME		20000			//摄像机的冷却时间
#define RECORDER_CHECK_COOLDOWN_TIME	20000			//检查录像检查的冷却时间
#define	GETBATTLEINFO_COOLDOWN_TIME	30000			//获取战场信息
#define QUERY_OTHER_ACHIEVMENT_COOLDOWN_TIME    10000          	//查看别人的成就的冷却时间 
#define CHANGE_DS_TIME			180000			//跨服请求的冷却时间

#define GET_MALL_PRICE_COOLDOWN_TIME		30000		//获取商城里哪些限时商品正在销售
#define GET_VIP_AWARD_INFO_COOLDOWN_TIME	15000		//获取VIP奖励信息冷却时间
#define RESET_SKILL_PROP_COOLDOWN_TIME		(24 * 3600 * 1000) //90级以下免费洗点洗天书冷却时间
#define ARRANGE_TRASHBOX_COOLDOWN_TIME          5000               //整理仓库的冷却时间
#define ARRANGE_INVENTORY_COOLDOWN_TIME         5000               //整理背包的冷却时间
#define ARRANGE_POCKET_COOLDOWN_TIME         	5000               //整理pocket的冷却时间

enum 
{
	COOLDOWN_INDEX_NULL,			//0
	COOLDOWN_INDEX_EMOTE,
	COOLDOWN_INDEX_DROP_MONEY,
	COOLDOWN_INDEX_DROP_ITEM,
	COOLDOWN_INDEX_SWITCH_FASHION,

	COOLDOWN_INDEX_ITEM_TELEPORT,		//5
	COOLDOWN_INDEX_QUERY_OTHER_EQUIP,
	COOLDOWN_INDEX_FIREWORKS,
	COOLDOWN_INDEX_FARCRY,
	COOLDOWN_INDEX_SKILL_TRIGGER,

	COOLDOWN_INDEX_DBL_EXP,			//10
	COOLDOWN_INDEX_SKILL_ITEM_1,
	COOLDOWN_INDEX_SKILL_ITEM_2,
	COOLDOWN_INDEX_SKILL_ITEM_3,
	COOLDOWN_INDEX_PK_RESET,

	COOLDOWN_INDEX_MOUNT,			//15
	COOLDOWN_INDEX_COUPLE_JUMP,
	COOLDOWN_INDEX_LOTTERY,
	COOLDOWN_INDEX_RECORDER,
	COOLDOWN_INDEX_RECORDER_CHECK,

	COOLDOWN_INDEX_TEAM_RELATION,		//20
	COOLDOWN_INDEX_CD_ERASER,
	COOLDOWN_INDEX_PET_COMBINE1,
	COOLDOWN_INDEX_PET_COMBINE2,
	COOLDOWN_INDEX_PICKUP,

	COOLDOWN_INDEX_SET_FASHION_MASK,	//25
	COOLDOWN_INDEX_GETBATTLEINFO,
	COOLDOWN_INDEX_HEALING_POTION,
	COOLDOWN_INDEX_MANA_POTION,
	COOLDOWN_INDEX_REJU_POTION,

	COOLDOWN_INDEX_STEP_HEALING,		//30
	COOLDOWN_INDEX_STEP_MANA,
	COOLDOWN_INDEX_STEP_REJU,
	COOLDOWN_INDEX_QUERY_OTHER_ACHIEVMENT,
	COOLDOWN_INDEX_TRANSFORM,

	COOLDOWN_INDEX_NEWBIE_CHAT,		//35
	COOLDOWN_INDEX_CHANGE_DS,
	COOLDOWN_INDEX_DEITY_POTION,
	COOLDOWN_INDEX_STEP_DEITY,
	COOLDOWM_INDEX_GET_MALL_PRICE,

	COOLDOWM_INDEX_GET_VIP_AWARD_INFO,	//40
	COOLDOWN_INDEX_RESET_SKILL_PROP_SKILL,
	COOLDOWN_INDEX_RESET_SKILL_PROP_TALENT,
	COOLDOWN_INDEX_BATTLE_FLAG,
	COOLDOWN_INDEX_PLAYER_FIRST_EXIT_REASON,
	
	COOLDOWN_INDEX_BOTTLE_HP,	//45
	COOLDOWN_INDEX_BOTTLE_MP,
	COOLDOWN_INDEX_BOTTLE_DEITY,
	COOLDOWN_INDEX_SKILL_ITEM_4,
	COOLDOWN_INDEX_SKILL_ITEM_5, 

	COOLDOWN_INDEX_BATH,	//50
	COOLDOWN_INDEX_KING_CALL_GUARD,
	COOLDOWN_INDEX_ARRANGE_INVENTORY,
	COOLDOWN_INDEX_ARRANGE_TRASHBOX,
	COOLDOWN_INDEX_TELEPORT1,	//祝福传送

	COOLDOWN_INDEX_TELEPORT2,	//诅咒传送, 55
	COOLDOWN_INDEX_CHANGE_PUPPET_FORM,	//傀儡姿态切换冷却限制
	COOLDOWN_INDEX_CIRCLE_OF_DOOM,	//结阵冷却
	COOLDOWN_INDEX_ARRANGE_POCKET,

	COOLDOWN_INDEX_PRODUCE_BEGIN 	= 600,
	COOLDOWN_INDEX_PRODUCE_END 	= 800,

	//组合技编辑
	COOLDOWN_INDEX_COMBINE_BEGIN	= 900,
	COOLDOWN_INDEX_COMBINE_END	= 950,

	COOLDOWN_SPEC_ERROR1 = 1023,
	COOLDOWN_SKILL_START = 1024,
	COOLDOWN_INDEX_CHEATER = 997,
	COOLDOWN_INDEX_ANTI_CHEAT = 998,
};

#endif

