#ifndef __SKILL_PLAYERWRAPPER_H
#define __SKILL_PLAYERWRAPPER_H

#include "common/types.h"
#include "obj_interface.h"
//#include "statedef.h"
//#include "../header/attack.h"

//#ifdef _SKILL_SIMULATION 
//#define VIRTUALFUN virtual
//#else
//#define VIRTUALFUN
//#endif

#ifdef WIN32
#ifndef uint
#define uint unsigned int
#endif // !uint
#endif

#include "skillfunction.h"

namespace GNET
{
	// 
class Skill;
class SkillWrapper;
//
//#define  COOLINGID_BEGIN 1024

	class PlayerWrapper;

	struct BuffLevelWrapper
	{
		PlayerWrapper* mPlayer;
		BuffLevelWrapper() : mPlayer(0) {}
	};

	class PlayerWrapper
	{
	//public:
	//	typedef unsigned int	SID;
	protected:
		object_interface object;
		char    context;   // 0:施法者 1:被施法者 2:被动技能生效 3:被动技能失效 4:被动技能学习
		Skill * skill;
		BuffLevelWrapper buffwrapper;
		const XID * target;
		int         tsize;
		
		//TargetInfoWrapper _targetinfo;
		
		// 临时参数
		float	probability;	// 状态攻击参数
		float	ratio;		// 状态攻击参数
		float	amount;		// 状态攻击参数
		float	value;		// 状态攻击参数
		int 	time;		// 持续时间
		//bool 	tiny_time;		 
		int     buffid;		// 是否显示状态图标
		
		XID caster;
		int     health;         // 治疗生命值
		//bool    success;
		//bool    immune;
		int result;
		int atstate;
		bool    invader;
		
		//bool	succaddfilter;
		int var[16];  //0x50  = 80
		int resistance_proficiency[6];  //0x90  = 144

	public:
		PlayerWrapper(
			object_interface,
			char _type,
			Skill* _s,
			const XID* _target,
			int _size);
		~PlayerWrapper();
		bool SetDisperseanti(bool a2);
		int GetDarklight();
		bool SetDiscover(bool a2);
		bool SetFrenzied(bool a2);
		void SetVar2(int v);
		void SetVar1(int v);
		bool SetSecondattack(bool a2);
		bool SetQilinform(bool a2);
		bool SetClearcooldown(bool a2);
		bool SetInsanityform(bool a2);
		bool SetDizzytimer(bool a2);
		bool SetDsleep(bool b);
		void SetVar6(int v);
		bool SetDrunk(bool a2);
		int GetVar4();
		bool SetDamagemove(bool a2);
		bool SetPasaddattack(float inc);
		int GetAtkrate();
		bool SetUniqprompt(bool a2);
		void SetVar10(int v);
		bool SetTongxin(bool);
		bool SetPasaddsleep(float);
		bool SetSubantiwrap2(bool);
		bool SetSharestatewithclone(bool);
		bool SetDecskillaccu(bool);
		bool SetYuanling(bool);
		bool SetIceshield(bool);
		bool SetSleep(bool);
		bool SetCycsubattack(bool);
		bool SetBaradddogeaccu(bool);
		bool SetJumptospouse(bool);
		bool ThrowDiceDiet(void);
		bool SetBounceto(bool);
		bool SetPasincpetdamage(float);
		int TakeOutItem(int, int, int);
		bool IsXuanYuan(void);
		bool SetMp(float);
		bool SetEnmity(int);
		void SetVar16(int);
		bool SetMpdisperse(bool);
		bool SetDimming(bool);
		bool SetInchurt2(bool);
		void DoPerform(void);
		bool SetBreakcasting(bool);
		bool IsFlying(void);
		bool SetCycsubdefence(bool);
		int GetAttackHigh(float, float);
		bool SetDarkuniform(bool);
		bool SetAddantisilent(bool);
		bool SetAddattack4(bool);
		bool SetHpleak2(bool);
		bool SetSetskilllevel(bool);
		bool SetHpregain(bool);
		int GetForm(void);
		int GetReborncount(void);
		bool SetDarkness(bool);
		bool SetTriggerskill(bool);
		bool SetExpboost(bool);
		bool SetUnsummon(bool);
		bool SetNingjin(bool);
		bool SetAmount(float);
		bool SetClearbuff(bool);
		bool SetBarexpboost(bool);
		float GetCrithurt(void);
		bool SetBarmpgen(bool);
		int GetAttackLow(float, float);
		bool SetShadowdance(bool);
		bool SetPowerless(bool);
		bool SetPasaddweaktenaciy(float);
		int GetVar3(void);
		bool SetSubhp(bool);
		bool SetTalismaneffects(bool);
		int GetVar8(void);
		bool SetSalvation(bool);
		bool SetTeamenchant(bool);
		bool SetImmunesleep(bool);
		void SendResult(XID const&, int);
		float GetSaint(void);
		bool CanCharge(XID const&, A3DVECTOR const&, char, float);
		bool SetDecaccuracy(bool);
		int GetSkilllevel(int);
		int GetCyclemembercnt(void);
		bool SetSkillreflect(bool);
		bool SetWraptimer(bool);
		bool SetDectp(int);
		bool SetReturnpos(bool);
		bool SetPasadddizzytenaciy(float);
		bool SetSummonteleport2(bool);
		bool SetParalysis(bool);
		int GetRes6(void);
		bool SetAutorescurrect(bool);
		void SetVar9(int);
		bool SetBlowoff(bool);
		bool SetInchpgen(bool);
		int GetDebuffcnt(void);
		bool IsBindState(void);
		bool SetPasdecfatalhurt(float);
		int IsMarried(void);
		int GetVar9(void);
		bool SetPasincskillaccu(float);
		bool SetVipguilin(bool);
		bool SetClearslow(bool);
		bool IsFilterExist(int);
		bool SetDirecthurt(bool);
		bool SetIncskilldamage(bool);
		bool SetMirrorimage(bool);
		bool SetAddcharm(bool);
		bool SetDeccrithurt(bool);
		bool SetDecdamage(bool);
		int GetCultivation(void);
		int GetDp(void);
		bool SetMagicdoor(bool);
		bool SetPasdechurt3(float);
		bool SetFamilyincattack(bool);
		bool SetIncfatalratio(bool);
		bool SetActiveonfilteradd(bool);
		bool SetCrazy(bool);
		bool SetAdddefence(bool);
		bool SetHupo(bool);
		bool SetImmuneweak(bool);
		bool SetRepel2(bool);
		bool GetHasbuff(int);
		bool SetGuishen2debuff(bool);
		bool SetHpleak1(bool);
		bool SetSubantiweak(bool);
		bool SetPassubhurt(float);
		bool IsMaster(void);
		void SetVar8(int);
		int GetInk(void);
		void SetRage(int);
		void SetTalentData(int*);
		bool SetPasinchpgen(float);
		bool SetDechurt2(bool);
		bool SetIncskillaccu(bool);
		bool SetPasaddaccuracy(float);
		bool SetSummonskill(bool);
		bool SetImmunesilent(bool);
		bool GetHasmultbuff(int);
		void SetSkill(Skill* s);
		bool SetPasaddslow(float);
		bool CheckItem(int, int, uint);
		float GetAmount(void);
		bool SetSummonclone(bool);
		bool SetReduceskillcd(bool);
		int GetCrit(void);
		bool SetJuniordarkform(bool);
		bool SetCrazycurse(bool);
		bool SetDecProficiency(uint, int);
		bool SetInvader(bool);
		bool SetClearwrap(bool);
		bool SetPuppetform(bool);
		bool SetGohome(bool);
		bool SetSharelifewithsummon(bool);
		int GetRes5(void);
		int GetMaxmp(void);
		bool SetGtmpgen(bool);
		bool SetSilenttimer(bool);
		bool SetSubattack(bool);
		float GetProbability(void);
		bool SetCrippleddebuff(bool);
		bool SetSpytrap(bool);
		bool SetFamilyincmp(bool);
		int GetHp(void);
		bool SetPasdecrestrainfo(float);
		bool SetSubdefence(bool);
		int GetPuppetid(void);
		int GetAtstate(void);
		void RemoveMultiFilter(int);
		bool SetBuffid(int);
		bool SetMakecrit(bool);
		bool SetAddattack3(bool);
		bool SetCursed(bool);
		bool SetRejectdebuff(bool);
		void CalcCost(void);
		void DoExoricism(int);
		bool UseMp(int);
		int GetVar1(void);
		bool SetHuju(bool);
		bool SetCreateobject(bool);
		bool SetSubantidizzy(bool);
		int64_t GetDTExp(void);
		bool SetDie(bool);
		bool SetAdddodge2(bool);
		bool SetDrawto(bool);
		bool SetSubantisleep(bool);
		bool SetActivebecrit(bool);
		bool CanAttack(void);
		void SetVar3(int);
		bool SetSubantislow(bool);
		bool SetHeal(bool);
		void SetDarklight(int);
		int GetDmgreduce(void);
		int GetSkillrate(void);
		int GetMp(void);
		bool SetBackorigin(bool);
		bool SetCleartransform(bool);
		bool SetSharelifewithclone(bool);
		bool GetIsfrozen(void);
		bool SetXinmo(bool);
		bool SetAddcommon(bool);
		bool SetDelaycast(bool);
		bool SetAddspirit(bool);
		bool SetLongxiang(bool);
		bool SetSubhp2(bool);
		bool SetInchp2(bool);
		bool SetInstantskill(bool);
		bool SetHpleak6(bool);
		bool SetGuishen1(bool);
		bool SetAdddebuff(bool);
		bool SetDrainmagic(bool);
		bool SetPasincmp(float);
		bool SetBlessed(bool);
		bool SetStateexchangewithclone(bool);
		bool SetPasincattack(float);
		bool SetChihun(bool);
		bool SetTransform(bool);
		bool SetPulling(bool);
		bool SetPasincmpgen(float);
		bool SetPasdecpethurt(float);
		float GetSpeed(void);
		float GetValue(void);
		bool GetInrange(float, float&, bool);
		bool SetCycle(bool);
		bool SetBarhpgen(bool);
		bool SetIncskilllevel(bool);
		bool SetAddwrap(bool);
		bool SetAddattack2(bool);
		bool SetDeccritrate(bool);
		bool SetInchp(bool);
		bool SetDecskilldodge(bool);
		int GetRace(void);
		bool SetIncattack3(bool);
		bool SetActivecrit(bool);
		void SetResisProf(int, int);
		bool SetFly(bool);
		bool SetBepulled(bool);
		bool SetAddhp(bool);
		bool SetPasaddmp(float);
		bool SetAddantiweak(bool);
		bool SetIncanti(bool);
		bool SetPasaddwrap(float);
		bool SetFamilyinchp(bool);
		int GetBuffcnt(void);
		bool SetSetcommondata(bool);
		bool SetAccumdamage(bool);
		bool SetSpicy(bool);
		bool SetAsfire(bool);
		int GetVar2(void);
		const XID& GetXid(void);
		bool SetAddslow(bool);
		int GetMaxhp(void);
		bool SetPasaddhp(float);
		bool SetDechurt(bool);
		bool SetDouhun(bool);
		bool SetAddantidizzy(bool);
		bool SetJuqi(bool);
		int GetSkilldodge(void);
		bool SetAoshi(bool);
		bool SetPasdechurt2(float);
		bool SetAdddodge(bool);
		int GetVar7(void);
		bool SetFocusanti(bool);
		bool SetAddanti2(bool);
		bool SetGuishen2(bool);
		bool SetSpeedto(bool);
		bool SetYanyu(bool);
		bool SetBanruo(bool);
		bool SetSetcooldown(bool);
		bool SetPasdecrestrainxian(float);
		bool SetWeak(bool);
		bool SetHp(float);
		bool SetTime(float);
		bool SetCycdecdefence(bool);
		bool SetXiaoxin(bool);
		bool ThrowDice(void);
		int GetRes3(void);
		bool SetAbsulotearea(bool);
		bool SetPasaddsilent(float);
		bool SetClearsleep(bool);
		bool SetCycleskill(bool);
		bool SetRandcurse(bool);
		bool CheckItem(int, uint);
		bool SetPasincskilldodge(float);
		bool SetHumanbomb(bool);
		bool SetThrowback(bool);
		bool SetCreateitem(bool);
		bool SetAloof(bool);
		bool SetJuniorlightform(bool);
		int GetGender(void);
		bool SetSummonteleport1(bool);
		float GetRange(void);
		bool SetCibei(bool);
		bool SetDecdrugeffect(bool);
		bool SetIncmpgen(bool);
		bool SetTiansha(bool);
		bool SetGoback(bool);
		bool SetBleeding(bool);
		bool SetDivinityfury(bool);
		bool SetEquipeffect(bool);
		bool SetFrozen(bool);
		bool SetPasdechurt1(float);
		bool SetHpleak3(bool);
		int GetDodge(void);
		bool SetPerform(int);
		bool SetAddantislow(bool);
		bool SetAddweak(bool);
		bool SetDecdodge(bool);
		bool SetMpleak(bool);
		bool SetAddspot(bool);
		bool SetZhaoqi(bool);
		int GetVar16(void);
		bool SetSeed(bool);
		bool SetSubantisilent(bool);
		bool IsRenMa(void);
		bool UseDp(int);
		bool SetTuoling2(bool);
		bool SetSleeptimer(bool);
		bool SetMiracleburstfo(bool);
		bool SetHpgen(bool);
		bool SetAssault(bool);
		bool SetSummontrap(bool);
		bool SetAswind(bool);
		int GetHide(void);
		bool GetIsignite(void);
		void SetVar7(int);
		bool SetJaillimitcyclearea(bool);
		bool SetCatchpet(bool);
		bool SetJailpermitcyclearea(bool);
		bool SetPossummon(bool);
		bool SetSubantidizzy2(bool);
		int TakeOutItem(int, int);
		bool SetFogstate(bool);
		bool SetDodge(bool);
		bool SetHpleak4(bool);
		bool SetAddantiwrap(bool);
		bool SetRmhumanform(bool);
		bool GetSuccess(void);
		bool SetIgnite(bool);
		bool SetDiet(bool);
		void SetVar(int, uint);
		bool SetRepel(bool);
		bool SetContext(char);
		bool SetPasadddefence(float);
		bool SetAttack2hp(bool);
		bool CheckTarget(float, bool);
		bool SetTuoling1(bool);
		bool SetIncattack(bool);
		bool SetPasadddizzy(float);
		bool SetFoxstate(bool);
		bool SetHolyaura(bool);
		bool SetPuppetskill(bool);
		bool SetShadowhide(bool);
		bool SetInccritrate(bool);
		bool SetImmuneslow(bool);
		int GetRegionReputation(int);
		bool SetDecsp(int);
		int GetRage(void);
		int GetSglevel(void);
		bool SetRatio(float);
		bool SetIncmp(bool);
		bool SetSilent(bool);
		bool SetPasdecrestrainmo(float);
		bool SetBarehanded(bool);
		bool SetDizzy(bool);
		bool SetGloss(bool);
		void SetVar5(int);
		int GetOccupation(void);
		bool SetTurnbuff(bool);
		bool SetPray(int);
		bool SetSeniordarkform(bool);
		bool SetDecfatalratio(bool);
		bool SetPasinchp(float);
		int GetMaxdp(void);
		bool SetTalismaneffectsbless(bool);
		bool SetPosexchangewithclone(bool);
		bool SetGtaddattackdefense(bool);
		bool SetSubantisilent2(bool);
		bool SetScopedamage(bool);
		bool SetSkillmirror(bool);
		bool SetSlow(bool);
		bool SetAddantisleep(bool);
		bool SetDeathscatter(bool);
		bool SetSpiritdrag(bool);
		int GetTmplid(void);
		bool SetImmunewrap(bool);
		bool SetClearweak(bool);
		void SetVar4(int);
		bool SetPasaddsmite(float);
		void SetCaster(XID const&);
		bool SetTurndebuff(bool);
		int GetVar10(void);
		bool SetPasincantislow(float);
		void ConsumeItem(void);
		void UseHp(int);
		bool SetRetort(bool);
		bool SetAsforest(bool);
		bool SetAddspeed(bool);
		bool SetJail(bool);
		bool SetAddrage2(bool);
		bool SetAttack2mp(bool);
		bool SetImmunedizzy(bool);
		bool SetBuxiu(bool);
		void SetVar11(int);
		bool SetPasdechurt(float);
		int GetLevelSum(int);
		bool SetTiangu(bool);
		bool IsCloneExist(void);
		bool SetDodgeregain(bool);
		bool SetCleardizzy(bool);
		bool SetSubantiwrap(bool);
		bool SetSwift(bool);
		int GetMaxatk(void);
		bool SetBloodthirsty(bool);
		bool SetAshill(bool);
		bool SetAddhp2(bool);
		int GetVar11(void);
		void AddGroupAttackExcludeMonsterTids(std::vector<exclude_target>& vec);
		bool SetIncmountspeed(bool);
		bool SetRecordpos(bool);
		bool IsMount(void);
		bool SetPasaddanti(float);
		bool SetAddmp(bool);
		bool SetSubanti(bool);
		bool SetCycdecattack(bool);
		int GetBaseLevel(int);
		bool SetGangdan(bool);
		bool SetFashen(bool);
		int GetLevel(void);
		void SetProbability(float);
		bool UseInk(int);
		int GetResisProf(int);
		bool SetCurseteleport(bool);
		int GetVar6(void);
		void ModifyRegionReputation(int, int);
		bool SetBloodthirsty2(bool);
		bool SetUpdatecommondata(bool);
		int GetDarklightform(void);
		bool SetMiracleburstxian(bool);
		bool SetMagicshield(bool);
		bool SetAddanti(bool);
		bool SetSummon(bool);
		bool SetUnsummonclone(bool);
		bool SetIncdefence(bool);
		bool SetSummonmachine(bool);
		bool SetPasinccrit(float);
		bool SetRecoverhp(bool);
		bool SetExorcism(bool);
		bool GetInrange(A3DVECTOR&, float, float, float&);
		bool ThrowDice(int);
		bool SetDecDeityExp(int);
		bool GetIscrit(void);
		bool IsMultiFilterExist(int);
		bool SetPasadddodge(float);
		bool SetAddattack(bool);
		bool SetGuilin(bool);
		int GetRes1(void);
		int GetVar5(void);
		bool SetDecfatalhurt(bool);
		int GetRes4(void);
		bool SetFiring(bool);
		bool SetExtracthp(bool);
		bool SetIncdrugeffect(bool);
		int GetMinatk(void);
		bool SetCleardebuff(bool);
		bool SetDecanti(bool);
		bool SetLightuniform(bool);
		bool SetBloodshield(bool);
		bool SetIncfatalhurt(bool);
		int GetType(void);
		bool SetInccrithurt(bool);
		void AddCommonDebuff(int, int, int, int, bool);
		bool SetPullback(bool);
		bool SetSubhide(bool);
		bool GetInrange(XID const&, float, float&, bool);
		bool SetIncskilldodge(bool);
		bool SetDivinityburst(bool);
		bool SetDeadlybless(bool);
		bool SetClearsilent(bool);
		bool SetColdinjure(bool);
		bool SetEvilaura(bool);
		bool SetSubmp(bool);
		bool SetWrap(bool);
		bool SetPasdecfatalratio(float);
		bool SetAddrage1(bool);
		bool GetInteam(void);
		bool SetMpgen(bool);
		bool SetViphupo(bool);
		bool SetBefired(bool);
		bool SetPasaddweak(float);
		bool SetFear(bool);
		bool SetInchurt(bool);
		bool SetValue(float);
		bool SetDispel(bool);
		bool SetAssault2(bool);
		bool SetHpleak5(bool);
		bool SetSubantisleep2(bool);
		bool SetInvincible(bool);
		int GetRes2(void);
		bool SetGhostform(bool);
		bool SetBloodpool(bool);
		bool SetMiracleburstmo(bool);
		bool SetSeniorlightform(bool);
		bool SetHpleak(bool);
		bool SetDecskilldamage(bool);
		bool SetDecdefence(bool);
		bool TargetIsSpouse(void);
		bool SetGthpgen(bool);
		int GetDef(void);
		int GetBufflevel(int);
		bool SetDecmp(bool);
		bool SetResurrect(bool);
		bool SetInchitrate(float);
		bool SetBreak(bool);
		bool SetScaleinchp(bool);
		bool SetScaleincmp(bool);
		bool SetScaledechp(bool);
		bool SetScaledecmp(bool);
		bool SetPasincefence(float);
		bool SetPasaddsilenttenaciy(float);
		bool SetPasaddsleeptenaciy(float);
		bool SetPasaddslowtenaciy(float);
		bool SetPasaddwraptenaciy(float);
		bool SetPasaddsilentproficiency(float);
		bool SetPasaddweakproficiency(float);
		bool SetPasadddizzyproficiency(float);
		bool SetPasaddsleepproficiency(float);
		bool SetPasaddslowproficiency(float);
		bool SetPasaddwrapproficiency(float);
		bool SetOverawe(bool);
		bool SetPowerup(bool);
		bool SetShouyi(bool);
		bool SetPasincantidizzy(float);
		bool SetPasincantiweak(float);
		bool SetPasincantiwrap(float);
		bool SetPasincantisilent(float);
		bool SetPasincantisleep(float);
		bool SetPasincanti(float);
		bool SetIncheal(bool);
		bool SetDirectattack(bool);
		bool SetPasdechurt4(float);
		bool SetPasdechurt5(float);
		bool SetPasdechurt6(float);
		bool SetCreditboost(bool);
		bool SetHurtscatter(bool);
		bool SetIncattack2(bool);
		bool SetSlow2(bool);
		bool SetIncdefence2(bool);
		bool SetExtractmp(bool);
		bool SetImmunetransform(bool);
		bool SetPasaddtransform(float);
		bool SetPasincantitransform(float);
		bool SetAddantitransform(bool);
		bool SetSubantitransform(bool);
		bool SetDrawclonelife(bool);
		bool SetBackstab(bool);
		bool SetCritcurse(bool);
		bool SetSubSpot(bool);
		bool SetAddhide(bool);
		bool GetIsfury(void);
		bool SetPasincdpgen(float);
		bool SetCrippled(bool);
		bool SetPermitcyclearea(bool);
		bool SetLimitcyclearea(bool);
		bool SetGuishen1debuff(bool);
		bool SetTuoling1debuff(bool);
		bool SetTuoling2debuff(bool);
		bool SetPzmaxspeed(bool);
		bool SetPzhalfspeed(bool);
		bool SetPzhill(bool);
		bool SetPznomove(bool);
		bool SetPzchaos(bool);
		bool SetPzvoid(bool);
		bool SetActivebeattacked(bool);
		BuffLevelWrapper* GetBufflevel(void);
		bool SetDarklaser(bool);
		bool SetDirstate(bool);
		bool SetShowyb(bool);
		bool SetSummoncontroltrap(bool);
		bool SetSubantiweak2(bool);
		bool SetSubantislow2(bool);
		bool SetSubmp2(bool);
		bool SetRenma1(bool);
		bool SetRenma2(bool);
		bool SetRenma3(bool);
		bool SetRenma4(bool);
	};


}

#endif

